import {
  Sprout,
  Cherry,
  MessageCircle,
  Wind,
  Rocket,
  Crown,
  BookOpen,
  Heart,
  Map,
  Trophy,
  Settings,
  ArrowRight,
  ChevronRight,
  ChevronLeft,
  Volume2,
  X,
  Star,
  Check,
  Search,
  Leaf,
  Sun,
  Flame,
  CircleHelp,
  Download,
  RotateCcw,
  Play,
  Pause,
  Home,
  Sparkles,
  Eye,
  Menu,
  CheckCheck,
  ArrowUpRight,
} from 'lucide-react';
const icons = {
  sprout: Sprout,
  cherry: Cherry,
  message: MessageCircle,
  kite: Wind,
  rocket: Rocket,
  crown: Crown,
  book: BookOpen,
  heart: Heart,
  map: Map,
  trophy: Trophy,
  settings: Settings,
  arrow: ArrowRight,
  right: ChevronRight,
  left: ChevronLeft,
  volume: Volume2,
  close: X,
  star: Star,
  check: Check,
  search: Search,
  leaf: Leaf,
  sun: Sun,
  flame: Flame,
  help: CircleHelp,
  download: Download,
  reset: RotateCcw,
  play: Play,
  pause: Pause,
  home: Home,
  sparkles: Sparkles,
  eye: Eye,
  menu: Menu,
  checks: CheckCheck,
  external: ArrowUpRight,
};
export type IconName = keyof typeof icons;
export function Icon({
  name,
  size = 22,
  className = '',
}: {
  name: IconName;
  size?: number;
  className?: string;
}) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={1.8} className={className} aria-hidden="true" />;
}
