export type ReadingCard = { id: string; text: string; hint: string; emoji: string; levelId: number; lessonId: string };
export type Lesson = { id: string; title: string; cards: ReadingCard[] };
export type Level = { id: number; title: string; subtitle: string; description: string; color: string; icon: string; lessons: Lesson[] };
type CardInput = [string, string, string];
const lesson = (levelId: number, index: number, title: string, inputs: CardInput[]): Lesson => ({
  id: `${levelId}-${index}`, title,
  cards: inputs.map(([text, hint, emoji], cardIndex) => ({ id: `${levelId}-${index}-${cardIndex}`, text, hint, emoji, levelId, lessonId: `${levelId}-${index}` })),
});
export const levels: Level[] = [
  { id: 1, title: 'Pierwsze słowa', subtitle: 'Tu zaczyna się przygoda', description: 'Bliskie osoby, zwierzęta i rzeczy. Poznaj słowa, które są wokół ciebie.', color: 'mint', icon: 'sprout', lessons: [
    lesson(1, 1, 'Mój mały świat', [['mama','Przytula cię i jest blisko.','👩'],['tata','Możesz z nim wybrać się na spacer.','👨'],['dom','Tu mieszkamy.','🏡'],['kot','Mruczy i ma wąsy.','🐈'],['pies','Macha ogonem.','🐕'],['miś','Pluszowy przyjaciel do przytulania.','🧸']]),
    lesson(1, 2, 'Pyszne słowa', [['jabłko','Okrągły owoc z drzewa.','🍎'],['banan','Żółty owoc w skórce.','🍌'],['woda','Pijemy ją, gdy chce nam się pić.','💧'],['chleb','Robimy z niego kanapki.','🍞'],['mleko','Biały napój.','🥛'],['gruszka','Owoc z wąską górą i szerokim dołem.','🍐']]),
    lesson(1, 3, 'Na podwórku', [['słońce','Świeci wysoko na niebie.','☀️'],['drzewo','Ma pień, gałęzie i liście.','🌳'],['kwiat','Rośnie w ogrodzie i pięknie pachnie.','🌷'],['piłka','Możesz ją kopać i łapać.','⚽'],['rower','Ma dwa koła i pedały.','🚲'],['motyl','Ma kolorowe skrzydła.','🦋']]),
    lesson(1, 4, 'Leśni przyjaciele', [['lis','Rudy mieszkaniec lasu.','🦊'],['sowa','Ptak, który pohukuje nocą.','🦉'],['jeż','Ma kolce na grzbiecie.','🦔'],['wilk','Wyje do księżyca.','🐺'],['żaba','Skacze i kumka nad stawem.','🐸'],['ślimak','Nosi muszlę na grzbiecie.','🐌']]),
  ]},
  { id: 2, title: 'Słowa do pary', subtitle: 'Razem znaczą więcej', description: 'Połącz dwa słowa i odkrywaj kolory, wielkości oraz nowe znaczenia.', color: 'peach', icon: 'cherry', lessons: [
    lesson(2, 1, 'Kolorowy świat', [['rude lisy','Jakiego koloru są te leśne zwierzęta?','🦊'],['zielona żaba','Kumkający mieszkaniec stawu.','🐸'],['żółty banan','Owoc w kolorze słońca.','🍌'],['czerwone jabłko','Owoc w kolorze maków.','🍎'],['białe mleko','Jasny napój w szklance.','🥛'],['niebieska woda','Jaki kolor ma woda na obrazku?','💧']]),
    lesson(2, 2, 'Duże i małe', [['mały kot','Kociak dopiero poznaje świat.','🐱'],['duży pies','Czworonożny przyjaciel zajmuje sporo miejsca.','🐕'],['mała mysz','Drobne zwierzątko z długim ogonem.','🐭'],['wielki słoń','Zwierzę z trąbą.','🐘'],['mały dom','Przytulne miejsce do mieszkania.','🏡'],['duże drzewo','Jego korona sięga wysoko.','🌳']]),
    lesson(2, 3, 'Co lubimy?', [['ciepły koc','Otulisz się nim wieczorem.','🛏️'],['miękki miś','Przyjaciel do przytulania.','🧸'],['słodka gruszka','Pyszny owoc z sadu.','🍐'],['wesoły pies','Macha ogonem na powitanie.','🐶'],['dobry dzień','Dzień pełen miłych chwil.','☀️'],['moja książka','Lubię oglądać jej strony.','📖']]),
    lesson(2, 4, 'Małe odkrycia', [['złota gwiazda','Błyszczy na nocnym niebie.','⭐'],['leśna ścieżka','Prowadzi między drzewami.','🌲'],['kolorowy motyl','Przysiada na kwiatku.','🦋'],['wesoła żaba','Skacze do stawu.','🐸'],['szybki rower','Jedzie na dwóch kołach.','🚲'],['cichy las','Słychać w nim szelest liści.','🌲']]),
  ]},
  { id: 3, title: 'Małe zdania', subtitle: 'Mam coś do powiedzenia', description: 'Pierwsze krótkie zdania o przyjaciołach i codziennych przygodach.', color: 'lavender', icon: 'message', lessons: [
    lesson(3, 1, 'Kto co robi?', [['Kot śpi.','Co robi mruczący przyjaciel?','🐈'],['Pies biega.','Kto tak szybko przebiera łapami?','🐕'],['Mama czyta.','Kto zagląda do książki?','📖'],['Tata gotuje.','Kto przygotowuje obiad?','🍲'],['Lis skacze.','Co robi rudy mieszkaniec lasu?','🦊'],['Sowa patrzy.','Kto ma wielkie, uważne oczy?','🦉']]),
    lesson(3, 2, 'To jest mój świat', [['To jest dom.','Tu mieszkają bliskie osoby.','🏡'],['To moja piłka.','Co można turlać po trawie?','⚽'],['Mam nowy rower.','Na czym wybiorę się na przejażdżkę?','🚲'],['Lubię moje klocki.','Z czego buduję wieżę?','🧱'],['To moja mama.','Kto jest przy mnie?','👩'],['Mam małego misia.','Kogo mogę przytulić?','🧸']]),
    lesson(3, 3, 'Na łące', [['Słońce jasno świeci.','Co rozświetla łąkę?','☀️'],['Motyl tu lata.','Kto ma lekkie skrzydła?','🦋'],['Żaba robi hop.','Kto skacze nad wodą?','🐸'],['Pszczoła zbiera nektar.','Kto pracuje na kwiatach?','🐝'],['Kwiat ładnie pachnie.','Co poznajemy nosem?','🌷'],['Ślimak wolno pełznie.','Kto nigdzie się nie spieszy?','🐌']]),
    lesson(3, 4, 'Moje uczucia', [['Bardzo się cieszę.','Jak się czuję, gdy jest mi wesoło?','😊'],['Chcę się przytulić.','Czasem potrzebuję bliskości.','🤗'],['Lubię ci pomagać.','Razem jest nam łatwiej.','💛'],['Dziś czuję spokój.','Oddycham powoli i odpoczywam.','🌿'],['Czasem się boję.','Mogę powiedzieć o tym bliskiej osobie.','🫂'],['Jestem z siebie dumny.','Udało mi się spróbować czegoś nowego.','⭐']]),
  ]},
  { id: 4, title: 'Ciekawe historie', subtitle: 'Każde zdanie to odkrycie', description: 'Dłuższe zdania, więcej szczegółów i mnóstwo rzeczy do wyobrażenia.', color: 'sky', icon: 'kite', lessons: [
    lesson(4, 1, 'Dzień z przyjaciółmi', [['Mały kot śpi na kocu.','Gdzie odpoczywa kot?','🐈'],['Wesoły pies biega po parku.','Gdzie bawi się pies?','🐕'],['Mama czyta mi nową książkę.','Co robimy razem z mamą?','📖'],['Tata robi pyszną zupę pomidorową.','Co dziś będzie na obiad?','🍅'],['Moja siostra buduje wysoką wieżę.','Co powstaje z klocków?','🧱'],['Razem rysujemy wielkiego, zielonego smoka.','Jakie stworzenie pojawiło się na rysunku?','🐉']]),
    lesson(4, 2, 'Wycieczka do lasu', [['Rudy lis biegnie leśną ścieżką.','Którędy biegnie lis?','🦊'],['Pod drzewem rosną małe grzyby.','Co znaleźliśmy pod drzewem?','🍄'],['Wiewiórka chowa orzechy na zimę.','Po co wiewiórce zapasy?','🐿️'],['Sowa odpoczywa wysoko na gałęzi.','Gdzie siedzi sowa?','🦉'],['Mały jeż szeleści w liściach.','Co słychać obok ścieżki?','🦔'],['W plecaku mam wodę i kanapki.','Co zabieramy na wycieczkę?','🎒']]),
    lesson(4, 3, 'Cztery pory roku', [['Wiosną w ogrodzie kwitną tulipany.','Jakie kwiaty witają wiosnę?','🌷'],['Latem jemy słodkie, czerwone truskawki.','Jak smakują letnie owoce?','🍓'],['Jesienią liście spadają na ziemię.','Co dzieje się z liśćmi?','🍂'],['Zimą lepimy bałwana z białego śniegu.','Z czego powstaje bałwan?','⛄'],['Po deszczu na niebie widać tęczę.','Co ma tyle pięknych kolorów?','🌈'],['Wiatr delikatnie porusza gałęziami drzew.','Co kołysze gałęzie?','🌳']]),
    lesson(4, 4, 'Małe wielkie pomysły', [['Zbuduję domek z koca i krzeseł.','Jak zrobić kryjówkę w pokoju?','🏕️'],['Narysuję rakietę lecącą do gwiazd.','Dokąd poleci moja rakieta?','🚀'],['Upieczemy razem ciasteczka w kształcie serca.','Jaki kształt mają ciasteczka?','💛'],['Posadzę małą roślinę w żółtej doniczce.','Gdzie będzie rosła roślina?','🪴'],['Zrobię dla babci kolorową laurkę.','Kto dostanie mój rysunek?','💌'],['Z papieru powstanie moja własna łódka.','Z czego zrobię łódkę?','⛵']]),
  ]},
  { id: 5, title: 'Wielkie przygody', subtitle: 'Wyobraźnia nie ma granic', description: 'Odkrywaj niezwykłe miejsca, czytając rozbudowane, pełne przygód zdania.', color: 'rose', icon: 'rocket', lessons: [
    lesson(5, 1, 'Podróż w kosmos', [['Moja rakieta wystartowała z ogrodu i poleciała wysoko nad chmury.','Skąd wystartowała rakieta?','🚀'],['Przez okno widzę Ziemię, która wygląda jak niebieska piłka.','Do czego podobna jest Ziemia?','🌍'],['Na Księżycu zostawiam ślady butów w miękkim pyle.','Co zostaje po moich krokach?','🌙'],['Mały robot zaprasza mnie na herbatę do swojej stacji.','Kto zaprosił mnie na herbatę?','🤖'],['Liczymy razem gwiazdy, ale jest ich więcej niż naszych palców.','Dlaczego trudno policzyć gwiazdy?','✨'],['Wracam do domu, żeby opowiedzieć wszystkim o kosmicznej podróży.','Co zrobię po powrocie?','🏡']]),
    lesson(5, 2, 'Podwodny świat', [['W przezroczystej wodzie pływa ławica małych, srebrnych rybek.','Jakiego koloru są rybki?','🐟'],['Ciekawski delfin wyskakuje nad fale i wesoło macha ogonem.','Co robi delfin?','🐬'],['Na dnie morza krab ostrożnie spaceruje między muszelkami.','Gdzie spaceruje krab?','🦀'],['Ośmiornica schowała się za skałą i zerka na nas jednym okiem.','Gdzie ukryła się ośmiornica?','🐙'],['Żółw morski płynie powoli w stronę kolorowej rafy.','Dokąd płynie żółw?','🐢'],['W moim szkicowniku rysuję wszystkie zwierzęta spotkane pod wodą.','Jak zapamiętam morskich przyjaciół?','🎨']]),
    lesson(5, 3, 'Smocza dolina', [['Za wysoką górą mieszka smok, który uwielbia malinowe lody.','Jaki jest ulubiony deser smoka?','🐉'],['Zamiast ziać ogniem, wypuszcza z nosa wielkie bańki mydlane.','Co niezwykłego potrafi smok?','🫧'],['Pewnego ranka znajduje przed jaskinią małego, zagubionego kotka.','Kogo znalazł smok?','🐱'],['Otula go miękkim szalikiem i pyta, gdzie jest jego dom.','Jak smok pomaga kotkowi?','🧣'],['Lecą razem nad doliną, aż dostrzegają znajomy czerwony dach.','Co wypatrzyli podczas lotu?','🏡'],['Od tej pory kotek odwiedza smoka w każdą słoneczną sobotę.','Kiedy spotykają się przyjaciele?','☀️']]),
    lesson(5, 4, 'Tajemniczy ogród', [['Za starą furtką odkrywamy ogród pełen pachnących kwiatów.','Co kryje się za furtką?','🌸'],['Na środku ogrodu stoi fontanna, w której kąpią się wróble.','Kto korzysta z fontanny?','🐦'],['Między krzakami malin prowadzi wąska ścieżka z białych kamyków.','Z czego zrobiona jest ścieżka?','🪨'],['Ścieżka kończy się przy wielkim drzewie z domkiem na gałęzi.','Co znaleźliśmy na drzewie?','🌳'],['W środku czeka książka z mapą i zaproszeniem do nowej przygody.','Co czeka w domku?','🗺️'],['Siadamy wygodnie i wspólnie czytamy pierwszą stronę tajemniczej książki.','Co robimy na końcu wyprawy?','📖']]),
  ]},
  { id: 6, title: 'Czytam samodzielnie', subtitle: 'Cała historia należy do ciebie', description: 'Sześć fragmentów łączy się w jedną historię. Czytaj i odkrywaj, co będzie dalej.', color: 'sand', icon: 'crown', lessons: [
    lesson(6, 1, 'Lis i zagubiona gwiazda', [['Lis Leo nie mógł zasnąć. Za oknem jego norki coś delikatnie świeciło.','Co zauważył Leo?','🦊'],['Wyszedł na polanę i zobaczył małą gwiazdę. Leżała na mchu i cicho wzdychała.','Gdzie leżała gwiazda?','⭐'],['„Zgubiłam drogę do domu” — powiedziała gwiazda. Leo postanowił jej pomóc.','Dlaczego gwiazda była smutna?','🌌'],['Poprosił sowę o radę. Sowa wskazała najwyższe wzgórze w całym lesie.','Kto udzielił lisowi rady?','🦉'],['Na wzgórzu Leo uniósł gwiazdę wysoko. Wiatr porwał ją łagodnie prosto na niebo.','Jak gwiazda wróciła na niebo?','🌠'],['Od tej nocy jedna gwiazda mrugała do lisa szczególnie jasno. Leo wiedział, że to jego przyjaciółka.','Skąd lis wiedział, że gwiazda o nim pamięta?','💛']]),
    lesson(6, 2, 'Piknik pod chmurką', [['Lena i Kuba zaplanowali piknik. Spakowali koc, kanapki i koszyk jabłek.','Co dzieci zabrały na piknik?','🧺'],['W parku znaleźli miejsce pod wielkim dębem. Rozłożyli koc na miękkiej trawie.','Gdzie urządzili piknik?','🌳'],['Nagle na niebie pojawiła się ciemna chmura. Pierwsza kropla spadła Kubie na nos.','Jak zmieniła się pogoda?','🌧️'],['Szybko schowali jedzenie i pobiegli do domu. Trochę żałowali swojego pikniku.','Jak poczuli się po powrocie?','🏡'],['„Mam pomysł!” — zawołała Lena. Rozłożyła koc na podłodze w salonie.','Co wymyśliła Lena?','💡'],['Jedli kanapki i słuchali deszczu za oknem. Ten domowy piknik też był wspaniały.','Co sprawiło dzieciom radość?','🥪']]),
    lesson(6, 3, 'Odważny mały jeż', [['Jeż Tymek chciał poznać sąsiadów. Wstydził się jednak zapukać do ich drzwi.','Czego obawiał się Tymek?','🦔'],['Pewnego dnia znalazł przy ścieżce czerwony szalik. Wiedział, że należy do wiewiórki.','Co znalazł jeż?','🧣'],['Wziął głęboki oddech i podszedł do jej drzewa. Zapukał cichutko do małych drzwi.','Co pomogło mu zrobić pierwszy krok?','🌳'],['Wiewiórka bardzo się ucieszyła. „Szukałam go od rana! Wejdziesz na herbatę?” — zapytała.','Dlaczego wiewiórka się ucieszyła?','🐿️'],['Przy herbacie rozmawiali o lesie i ulubionych zabawach. Tymek powoli przestał się wstydzić.','O czym rozmawiali sąsiedzi?','☕'],['Wracając do domu, pomachał zającowi. Już wiedział, że przyjaźń zaczyna się od małego kroku.','Czego nauczył się Tymek?','🐇']]),
    lesson(6, 4, 'Nasionko niespodzianka', [['Babcia dała Mai małe nasionko. „Zasadź je i zobacz, co z niego wyrośnie” — powiedziała.','Co Maja dostała od babci?','🌱'],['Maja wsypała ziemię do doniczki i zrobiła mały dołek. Ostrożnie włożyła do niego nasionko.','Jak Maja zasadziła nasionko?','🪴'],['Każdego dnia sprawdzała ziemię i podlewała ją, kiedy była sucha. Przez kilka dni nic się nie działo.','Jak opiekowała się rośliną?','💧'],['Pewnego ranka zobaczyła dwa zielone listki. Pobiegła do babci podzielić się nowiną.','Co pojawiło się w doniczce?','🌿'],['Roślina rosła i rosła. W końcu otworzył się na niej wielki, żółty kwiat słonecznika.','Co wyrosło z nasionka?','🌻'],['Maja narysowała kwiat i podarowała rysunek babci. „Teraz obie mamy swój słonecznik!” — powiedziała.','Jak Maja podziękowała babci?','🎨']]),
  ]},
];
export const allCards = levels.flatMap(level => level.lessons.flatMap(lesson => lesson.cards));
export const allLessons = levels.flatMap(level => level.lessons);
